
# Lab-02 — PyTorch Tensors (Colab)
**AI Demystified: Decoding Models, Compute, and Connectivity**

**Goals:**

- (0D, 1D, 2D) tensors
- `dtype` specified at creation (no dtype conversion)
- `zeros`, `randn`, `shape`, `ndim`
- Autograd (with `t = 3`)
- Reshaping matrices
- Matrix multiplication
- 3D & 4D tensors (via `randn`)
- Broadcasting
- Batch matrix multiplication
- Creating on GPU and moving to device


## 1) Setup

**Note:** Tensors are the n-dimensional arrays used by deep-learning frameworks. In this lab we use **PyTorch**, but the core ideas—**shape**, **rank/ndim**, **dtype**, **broadcasting**, and **matrix multiplication** are essentially the same in **TensorFlow**. The main differences are just the APIs (e.g., `torch.tensor/zeros/randn` vs `tf.constant/zeros/random.normal`) and autograd (`y.backward()` in PyTorch vs `tf.GradientTape` in TensorFlow). So you can translate these examples to TensorFlow with minimal changes.

In [1]:
import torch

In [2]:
print(torch.__version__)

2.8.0+cu126


In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
print(device)

cpu


## 2) (0D, 1D, 2D) tensors — simple shapes & dtypes

In [5]:
t0 = torch.tensor(3.0)  # 0-D (scalar), float32 by default for floats

In [6]:
print(t0.shape)

torch.Size([])


In [7]:
print(t0.ndim)

0


In [8]:
t1 = torch.tensor([1, 2, 3])  # 1-D (vector), int64 by default for ints

In [9]:
print(t1.shape)

torch.Size([3])


In [10]:
print(t1.ndim)

1


In [11]:
t2 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

In [12]:
print(t2.shape)

torch.Size([2, 2])


In [13]:
print(t2.ndim)

2


In [14]:
z = torch.zeros(2, 3)

In [15]:
print(z.dtype)

torch.float32


In [16]:
z64 = torch.zeros(2, 3, dtype=torch.float64)

In [17]:
print(z64.dtype)

torch.float64


In [18]:
r = torch.randn(2, 3)

In [21]:
print(r)

tensor([[-1.0741,  0.5495, -0.1293],
        [-0.4020,  1.3252,  1.6812]])


In [19]:
print(r.shape)

torch.Size([2, 3])


In [22]:
print(r.ndim)

2


## 3) Autograd (x = 3)

In [34]:
x = torch.tensor([3.0], requires_grad=True)

In [35]:
y = x**2

In [36]:
print(y)

tensor([9.], grad_fn=<PowBackward0>)


In [37]:
y.backward()

In [38]:
print(x.grad)

tensor([6.])


## 4) Reshaping matrices

In [39]:
A = torch.arange(6.0)

In [40]:
print(A)

tensor([0., 1., 2., 3., 4., 5.])


In [41]:
print(A.shape)

torch.Size([6])


In [42]:
A2 = A.reshape(2, 3)

In [44]:
print(A2)

tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [45]:
print(A2.shape)

torch.Size([2, 3])


## 5) Matrix multiplication

In [46]:
M = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

In [47]:
N = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

In [48]:
P = M @ N

In [49]:
print(P)

tensor([[19., 22.],
        [43., 50.]])


In [50]:
print(P.shape)

torch.Size([2, 2])


## 6) 3D & 4D tensors (via randn)

In [51]:
T3 = torch.randn(2, 3, 4)  # e.g., (batch=2, features=3, time=4)

In [52]:
print(T3)

tensor([[[ 1.0846, -1.2932, -0.6506,  2.9998],
         [-0.7587, -1.2458, -0.2743,  1.3394],
         [-0.3426, -0.2543, -1.2460, -0.1131]],

        [[-0.1328, -1.7748, -0.4433,  0.8582],
         [-0.1563,  0.2075, -0.6709,  0.6556],
         [-0.0802, -0.5879, -0.0699, -1.1478]]])


In [53]:
print(T3.shape)

torch.Size([2, 3, 4])


In [54]:
print(T3.ndim)

3


In [55]:
T4 = torch.randn(2, 3, 4, 4)  # e.g., (B, C, H, W)

In [56]:
print(T4)

tensor([[[[-1.7681,  0.1464,  0.2776, -0.2465],
          [-0.0905, -0.1455, -1.0003, -1.2384],
          [-0.7756, -1.0499, -0.6796, -1.9621],
          [-0.0179, -0.2044,  0.4694, -1.0876]],

         [[ 0.2970, -1.0472,  0.2812,  0.3607],
          [ 1.6135,  0.8149,  1.3851, -0.9138],
          [-0.8317, -1.2714, -0.2471,  0.8166],
          [-2.5578,  1.0103, -1.6619, -0.8787]],

         [[ 1.7232, -1.0503, -0.5287, -0.0732],
          [ 2.3384,  1.1444, -0.0885, -0.1991],
          [ 1.1045,  1.1621,  0.5842, -1.4379],
          [-0.3069,  0.2424,  2.1984,  0.7756]]],


        [[[ 1.2193,  1.1503, -1.1929,  0.6111],
          [ 0.0470, -0.2154, -0.6514,  1.1084],
          [-0.6978, -0.9609,  0.7004,  2.8867],
          [-0.7734,  0.5336,  0.7180, -0.0803]],

         [[-0.0061, -0.7999, -1.6773, -0.2058],
          [ 1.5082,  1.3690,  1.0284,  0.4445],
          [ 0.6400,  0.9780,  2.2276, -0.8048],
          [ 0.0309, -0.0749,  2.1489, -1.1888]],

         [[ 0.6726, -2.5064,

In [57]:
print(T4.shape)

torch.Size([2, 3, 4, 4])


In [58]:
print(T4.ndim)

4


## 7) Linear model — broadcasting:  y_hat = W @ x + b

In [96]:
x = torch.tensor([[1],[2],[3]])

In [97]:
print(x.shape)

torch.Size([3, 1])


In [98]:
W = torch.tensor([[1,1,1],[1,1,1]])

In [99]:
print(W.shape)

torch.Size([2, 3])


In [100]:
print(W)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [106]:
b = torch.tensor(2)

In [107]:
print(b.shape)

torch.Size([])


In [108]:
y_hat = W @ x + b

In [109]:
print(y_hat)

tensor([[8],
        [8]])


In [110]:
print(y_hat.shape)

torch.Size([2, 1])


## 8) Batch matrix multiplication

In [111]:
A_b = torch.randn(4, 2, 3)  # (B=4, n=2, k=3)

In [112]:
B_b = torch.randn(4, 3, 5)  # (B=4, k=3, m=5)

In [113]:
C_b = torch.bmm(A_b, B_b)  # -> (4, 2, 5)

In [114]:
print(C_b.shape)

torch.Size([4, 2, 5])


## 9) Device — create on device and move existing tensor (no dtype conversion)

In [115]:
x_dev = torch.zeros(2, 2, device=device)

In [116]:
print(x_dev.device)

cpu


In [117]:
y_cpu = torch.randn(2, 2)

In [118]:
y_dev = y_cpu.to(device)

In [119]:
print(y_dev.device)

cpu



## 10) Mini‑Exercises — YOU type the answers

**E1.** Create a zeros tensor `img` with shape `(1, 3, 2, 2)` and dtype `float32`.  
Print `img.shape` in one cell and `img.ndim` in another.

**E2.** Create `A` with shape `(3, 2)` and `B` with shape `(2, 3)` using `randn`.  
Compute `C = A @ B` and print `C.shape` in a separate cell.

**E3.** Start with `Z = torch.arange(12.0)` → reshape to `(3, 4)` → reshape to `(2, 2, 3)`.  
Print shapes at each step (one print per cell).

**E4.** Batch matmul: create `A_b` with shape `(2, 2, 3)` and `B_b` with shape `(2, 3, 4)` via `randn`.  
Compute `C_b = torch.bmm(A_b, B_b)` and print `C_b.shape`.


In [132]:
# E1: your code here


In [133]:
# print(img.shape)


In [125]:
# print(img.ndim)


4


In [134]:
# E2: your code here


In [135]:
# print(C.shape)


In [ ]:
# E3: your code here


In [136]:
# E4: your code here


In [137]:
# print(C_b.shape)


### (Optional) Run checks

In [131]:

ok = True
try:
    ok &= (isinstance(img, torch.Tensor) and img.shape == (1,3,2,2))
    ok &= (C.shape == (3,3))
    ok &= (C_b.shape == (2,2,4))
except Exception:
    ok = False
print(ok)


True
